### ISSUE TITLE
Some problems about MPQ Library

### ISSUE THREAD

**Issue by 2360871791** [Drake53/War3Net#1]
1. About MPQ library unable to open the map of large size

2. MPQ cannot analyze the  imported file to make it unable to export, but can export the specified external file

**Comment by Drake53** [comment]
1. Does it throw an exception? If so, can you post the stack trace? It would be helpful if you could provide me with a map file that has this issue. If you don't have a place to upload it, you can add it [here](https://github.com/Drake53/War3Net/tree/master/tests/War3Net.IO.Mpq.Tests/TestArchives) and create a pull request.
2. Not sure what you mean by this. Maybe give an example?

**Comment by 2360871791** [comment]
1. MPQ's OK thank you

2.About the application of BLP library, at present, BLP can be converted to pictures of other formats, but it can't be converted to BLP from pictures of other formats. Can you add a conversion API for it?

**Comment by 2360871791** [comment]
1.MPQ operation supported.Thanks for your working
2.I have a question that the library can convert "blp format" to "other format", but can't convert "other format" to "blp format".
Could you add this feature? 
Look forward to your kind reply.

**Comment by 2360871791** [comment]
Look forward to your kind reply.

**Comment by Drake53** [comment]
For the BLP feature you could try [here](https://github.com/WoW-Tools/SereniaBLPLib/issues).

**Comment by 2360871791** [comment]
can MPQ lib import external file？

**Comment by Drake53** [comment]
To add files to an existing archive, you have to recreate it.
You can do this using the following methods:

- MpqArchive.GetMpqFiles()
- MpqFile.New(Stream, string)
- MpqArchive.Create(string, MpqFile[])
