### ISSUE TITLE
Issues on large mpq files

### ISSUE THREAD

**Issue by IceReaper** [Drake53/War3Net#10]
Problem lies here:
```public const int MaxSize = 0x1 << 15;```
On my particular mpq file, size is 65536, so << 16

**Comment by IceReaper** [comment]
To be a bit more specific on the files: Opening the "Installer Tome.mpq" from the WoW 1.0.0 discs.

**Comment by IceReaper** [comment]
I made a local Clone of this repo and changed the MaxSize constant. Worked flawless.

**Comment by Drake53** [comment]
Thanks, fixed by: 9b095fca322bf9578bf8dd16abd6723005c23b38
