### ISSUE TITLE
It's not very clear

### ISSUE THREAD

**Issue by VarionDrakon** [Drake53/War3Net#2]
Good day, the library is certainly great, but it is not clear how to use the same blp... It seems to have done everything correctly, but again does not want to open files... None at all... Please tell me if you need a code, I can provide it...

**Comment by Drake53** [comment]
Hi, I'm not sure what issue you're having, an example would be helpful.

**Comment by VarionDrakon** [comment]
Then can you show how to use it for example when opening the file selection window? The thing is I didn't understand anything.

**Comment by Drake53** [comment]
I can't give you an example if I don't know what your problem is about. Does it have anything to do with the war3mapMap.blp/war3mapPreview.blp files? If so, there are currently some issues with those in reforged (patch 1.32), so I can't really help you with that.

**Comment by VarionDrakon** [comment]
I'm trying to open blp files from WarCraft 1.26 using Your library... And I have already entered this code in the file opening, but no...

**Comment by Drake53** [comment]
You need to give more information if you want me to help you.
Are you trying to open the blp as a bitmap, bitmapsource, or skbitmap? Does it throw an exception? If so, post the stack trace. What's the target framework of your project? etc

**Comment by VarionDrakon** [comment]
https://drive.google.com/file/d/15ggZsNdBIqOlQUe0jrveCwM_JPjMFNei/view?usp=sharing

**Comment by Drake53** [comment]
I can't just guess what problem you're running into looking only at a small part of your project (I can see in the .csproj that you removed most files). All I see is that your application uses windows forms, so you want to use Bitmap, but instead you're opening the BLP file as SKBitmap.

**Comment by VarionDrakon** [comment]
How do I use bitmap instead of Skbitmap?

**Comment by Drake53** [comment]
Change
```csharp
blpFile.GetSKBitmap(mipMapLevel);
```
to
```csharp
blpFile.GetBitmap(mipMapLevel);
```

**Comment by VarionDrakon** [comment]
Why does it give an error about (fileStream)?

`var blpFile = new BlpFile(fileStream);`

**Comment by VarionDrakon** [comment]
And (mipMapLevel) writes that no... What Could I have missed?..

**Comment by Drake53** [comment]
About the fileStream, what is the error? If it's a compiler error, you may have forgotten to add:
```csharp
using var fileStream = File.OpenRead(open_dialog.FileName);
```
If it's a runtime error, what is the error message?

About the mipMapLevel: this is an optional parameter, the default value is 0. Remove it if you want to use the default value:
```csharp
blpFile.GetBitmap();
```

**Comment by VarionDrakon** [comment]
`CS0127 error Because "Main_Form.bLP1ToolStripMenuItem_Click (object, EventArgs)" returns a void value, so the object expression must not be present after the return keyword.`

**Comment by VarionDrakon** [comment]
And:
`System.ArgumentException
HResult=0x80070057
Message = Empty path name is not allowed.
Source = mscorlib
Stack trace:
in the system.IO.FileStream Type.Init(string path, filemode mode, the fileaccess access, int32 rights, Boolean useRights, fileshare share, int32 bufferSize, FileOptions options, in security_attributes secAttrs, string msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
in the system.And About. FileStream Storage..what (string path, filemode mode must be opened with the file access flags, exchange share)
in the system.IO. File. Open Read (string path)
in BLP_Editor_s. Main_Form.bLP1ToolStripMenuItem_Click(object sender, EventArgs e) in ...`

**Comment by VarionDrakon** [comment]
This is when you click on the open file dialog box...

**Comment by Drake53** [comment]
CS0127: https://stackoverflow.com/questions/12843501/error-returns-void-a-return-keyword-must-not-be-followed-by-an-object-expressi/12843684#12843684

The other error, I'm not sure, if you select a file the FileName property should not be empty. Maybe try using the OpenFileDialog.OpenFile() method instead.

**Comment by VarionDrakon** [comment]
I have something like this...
`  private void bLP1ToolStripMenuItem_Click(object sender, EventArgs e)
        {
            Bitmap GetBitmap; //Bitmap для открываемого изображения

            var fileContent = string.Empty;
            var filePath = string.Empty;

            using OpenFileDialog open_dialog = new OpenFileDialog();

            open_dialog.InitialDirectory = "c:\\";
            open_dialog.FilterIndex = 2;
            open_dialog.RestoreDirectory = true;
          //  open_dialog.FileName = "myText";
            open_dialog.Filter = "Image Files(*.BLP)|*.BLP|All files (*.*)|*.*"; //формат загружаемого файла
          open_dialog.FileName = "F:/Dev/BLP Editor/BLP Editor's/bin/Debug/BTNAbomination.blp";
            using var fileStream = File.OpenRead(open_dialog.FileName);

            { 
            var blpFile = new BlpFile(fileStream);
            var bitmap = blpFile.GetBitmap();
           
                    if (open_dialog.ShowDialog() == DialogResult.OK)
                    {
                        try
                        {
                        string filename = open_dialog.FileName;

                                    GetBitmap = new Bitmap(fileStream);   
                                    this.pictureBox1.Size = GetBitmap.Size;
                                    pictureBox1.Image = GetBitmap;
                                    pictureBox1.Invalidate();
                       }
                       catch
                       {
                                    DialogResult rezult = MessageBox.Show("Невозможно открыть выбранный файл",
                                    "Ошибка", MessageBoxButtons.OK, MessageBoxIcon.Error);
                       }
                    }
                return;
            }
        }`

**Comment by VarionDrakon** [comment]
Not work...

**Comment by VarionDrakon** [comment]
Drake53 Help Me)))

**Comment by Drake53** [comment]
https://stackoverflow.com/questions/ask

**Comment by VarionDrakon** [comment]
Good...
