### ISSUE TITLE
SylkTable.Parse cannot parse the comment(s) field in unitweapons.slk

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Net#21]
I noticed this while trying out the current iteration of War3Api.Object.Generator and thought it might be a 1.32 specific issue. I get the exception `System.NotSupportedException: Can only parse strings, integers, floats, and booleans.` I can share my unitweapons.slk file if that would be helpful. I tried parsing every other .slk file in the "units" folder and everything else worked.

**Comment by Drake53** [comment]
I don't have this problem with 1.31 data so it's probably an issue in 1.32, if you could share the value for which it throws or the entire .slk file that would be very helpful.

**Comment by YakaryBovine** [comment]
Excellent, I thought that was likely. Attaching a .zip only containing unitweapons.slk. I couldn't upload the .slk directly, sorry.
[unitweapons.zip](https://github.com/Drake53/War3Net/files/7598794/unitweapons.zip)

**Comment by Drake53** [comment]
Thanks, it appears that in addition to #VALUE!, there's now also #REF!
I have updated War3Net.IO.Slk to v0.1.3 with the fix.
