### ISSUE TITLE
get_ValueAsBool error when building map

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Net#23]
Hi, I get this error when I try to build my map:

![image](https://user-images.githubusercontent.com/8995690/164951524-c7c08a64-955e-44c3-b5e9-c0993b34aefd.png)

![image](https://user-images.githubusercontent.com/8995690/164951541-94ed11a3-c615-4554-8f89-78c3a62f0992.png)

Seems that it cannot conert the "ubdg" unit modification into a boolean. 

Here is my repo if you'd like to reproduce the error on your end. Just need to run the Launcher and hit 3.
https://github.com/YakaryBovine/AzerothWarsCSharp/tree/jass-transpiled

**Comment by Drake53** [comment]
ValueAsBool/etc doesn't actually convert the value, it only checks if the 'object Value' property is a bool. However, as you can also see from the Type property, it's actually an int. So it actually seems more like an issue with your war3map.w3u file which has saved an ubdg property as int, even though according to unitmetadata.slk this property should be a bool.

**Comment by YakaryBovine** [comment]
Cool, that makes sense. It wouldn't be the first time this map has had broken data. I'll just confirm before I close.

**Comment by YakaryBovine** [comment]
Ok, I don't think the problem is on my end. You can reproduce the issue on a new map like so:
1. Place a Way Gate on the map.
2. Place a region on the map.
3. Make the region the destination of the Way Gate. 
![image](https://user-images.githubusercontent.com/8995690/164973732-2cc8859c-6a63-49d1-9852-3efda8e9d04b.png)
4. Change the Way Gate unit type's Is a Building field to false. 
![image](https://user-images.githubusercontent.com/8995690/164973750-39aa6c05-27f7-4aea-adfa-bbcba4ddc7a4.png)

**Comment by Drake53** [comment]
Forgot this was a thing: https://github.com/Drake53/War3Api/issues/14
Should be fixed in v5.4.2: https://github.com/Drake53/War3Net/commit/4f6ac27da194106ee0eba1549468e4360ef65618

**Comment by YakaryBovine** [comment]
Yep, that fixed it and I can now build again. Thankyou!
