### ISSUE TITLE
Is there any way to code C# to compile to jass/lua script for a war3map?

### ISSUE THREAD

**Issue by Rabbb** [Drake53/War3Net#27]
Hey there. I'm a C# programer. I'm surprised to discovery a project that I never seen before, which can use C# language to code trigger scripts for develop war3map. But I  found that it's not like an offical project by blizzard, which is developing by personal developer. It's a magical project that I found. But I am heavy to starting coding,  which is the problem that I don't know how to create an trigger and call functions for my idea. Is there any guide to use those Api in this project? Thinks for your reply.

**Comment by Drake53** [comment]
I think this would be a good starting point: https://github.com/Orden4/WCSharp
That project also has a wiki that should help you get started.

**Comment by Rabbb** [comment]
Thanks for your help.  /: D
