### ISSUE TITLE
1.33 maps new object data format version

### ISSUE THREAD

**Issue by TheLazzoro** [Drake53/War3Net#29]
Loading maps saved with the 1.33 editor (PTR) throws the following exception:

'Value '3' is not defined for enum of type ObjectDataFormatVersion.'

It looks like Blizzard updated the format version for multiple object data files.

**Comment by Drake53** [comment]
Do you have an example map or file? I'm stuck on 1.31 so I can't test the PTR myself.

**Comment by TheLazzoro** [comment]
There you go:
https://www.hiveworkshop.com/pastebin/6ece1478634d078f9483620b74fb05f9.25056

**Comment by Drake53** [comment]
Thanks, it seems there are two new values at the object level. In your example map these are always set to 1 and 0 respectively.
Fix: https://github.com/Drake53/War3Net/commit/a99ea2f3e7686065166c238a5bd312244525e8c5

Can you see any new features in the object editor that may be using these new values?

**Comment by TheLazzoro** [comment]
There are no new fields in the object editor, but there are new 'war3mapSkin.w3*' files in the map MPQ . According to Bogdan from Hive Workshop these new files contain 'all netsafe fields'.

**Comment by Drake53** [comment]
Hadn't noticed those files before, I have included them in my tests: https://github.com/Drake53/War3Net/commit/4bf7c886c14d5592490dc04c75d23db87e9f65d8

Unfortunately the meaning of the new values remains a mystery.
If I had to guess maybe it has something to do with SD/HD graphics?

**Comment by TheLazzoro** [comment]
I am unsure, you would need to ask someone more qualified about this.

Thank you for addressing the issue though. I'm looking forward to the next NuGet update 👍
