### ISSUE TITLE
Implement .wgc

### ISSUE THREAD

**Issue by Luashine** [Drake53/War3Net#30]
Finished description here: https://github.com/Luashine/WC3MapSpecification/blob/pr-gameconfig/GameConfiguration/1.md

It's been a while since 2007:

1. https://www.hiveworkshop.com/threads/how-to-run-maps-with-high-gamespeed.37255/
2. https://www.wc3maps.com/InsideTheW3M.html

PS: Turns out I'm getting increasingly worse at reading comprehension, the wc3maps page has a complete format description, I thought it lacked the full description of `player slot flags`... That could've spared me an hour testing that bitfield.

**Comment by Drake53** [comment]
Do you have one or more example files that I can use to write the tests for this?

**Comment by Luashine** [comment]
Yes! How come I didn't think of that? [wc3-wgc.zip](https://github.com/Drake53/War3Net/files/9333298/wc3-wgc.zip)

**Comment by Luashine** [comment]
There's an error in the struct file above: **all integers must be unsigned**, I declared a few of them as signed by mistake during testing.

Fractional or <100% base game speeds are not possible, it's only an integer multiplier. Setting all speed bits to 1 causes a frozen game window that still plays day/night change sounds very often.

**Comment by Luashine** [comment]
Another error I caught while implementing this: if the player slot is specified as HUMAN PLAYER or OBSERVER then the "ai difficulty" int must have its LSB set to 1 (BitOR 0x01). If that bit is set to 0, the map will not load and the game will launch to main menu.

Updated file: [WGC_format-v1.txt](https://github.com/Drake53/War3Net/files/9340370/WGC_format-v1.txt)

**Comment by Drake53** [comment]
Thanks for the documentation and examples, here's the implementation: https://github.com/Drake53/War3Net/commit/0e9853a40f9290a1bfdc6b0ff800a3e4c0fddcb1

One thing I noticed is that the documentation on wc3maps.com that you linked states that flag 0x08 indicates an abolute path for the custom AI file, but yours says that it's relative. Based on the example files you provided I think your documentation is incorrect.

**Comment by Luashine** [comment]
You are right, I got the absolute/relative path flag wrong. Here's the correct description:

>bit 0x08 = AI file path is relative (0) or absolute (1)

I will change the docs now.
