### ISSUE TITLE
'Value '6115' is not defined for enum of type EditorVersion.'

### ISSUE THREAD

**Issue by TheLazzoro** [Drake53/War3Net#36]
'BinaryReaderExtensions' cannot read map info on upcoming 1.35 maps (PTR currently).

**Comment by Drake53** [comment]
Fixed in v5.5.7: https://github.com/Drake53/War3Net/commit/4191e9954119235d28b1f5c38da00f09583d1847
I read the patch notes and it seems the campaign file format may have been changed.
