### ISSUE TITLE
Map builder broken

### ISSUE THREAD

**Issue by TheLazzoro** [Drake53/War3Net#38]
After updating to the latest War3Net packages my map does not build properly.

None of the 'war3mapSkin' files are present in the output archive and all custom data is reset like unit names, models, icons, gold cost, requirements, abilities, upgrades etc. etc. (all data as far as I can tell).

I'm using Map.Open(mapDir) to load the map directory from scratch and MapBuilder.Build(path) to build the MPQ archive.
There's no loss of data when saving an archive with Blizzard's editor, so it's not my map that is broken.

I'm on the latest WC3 version btw.

**Comment by Drake53** [comment]
Thanks for reporting this, should be fixed in v5.7.1 with the following change: https://github.com/Drake53/War3Net/commit/bf0f4471ebf9db5076ea3520d625a4bd8c176eb1

**Comment by TheLazzoro** [comment]
Thank you so much, and thanks for all your work in general. This library has been essential for the development of my trigger editor :)
