### ISSUE TITLE
Pls fix

### ISSUE THREAD

**Issue by AzuStar** [Drake53/War3Net#4]
System.Exception
  HResult=0x80131500
  Message=An exception occured when trying to parse the 'war3map.w3a' file: Exception has been thrown by the target of an invocation.
  Source=ZombieSurvivalAlpha.Launcher

Steps to reproduce:
Create map, create custom ability, modify field(-s), save.

Latest version when it works fine 1.3.0
Version when it breaks 1.3.1
Reforged 1.32.6

also w3s, w3u

**Comment by AzuStar** [comment]
My bad, 1.3.0 breaks the thing and causes the error.

**Comment by Drake53** [comment]
That exception doesn't give me a lot of information, probably because I invoke the method using reflection. Can you upload your files? Or try testing them yourself by adding them to War3Net.Build.Tests at TestData\Object\Ability, TestData\Object\Unit, TestData\Audio for the .w3a, .w3u, and .w3s files respectively.
Also, you say it breaks on 1.3.0 and 1.3.1, have you tried on 1.3.4?

**Comment by AzuStar** [comment]
It was breaking on all version above 1.3.0 at the moment of making the issue.
The issue seems to be related to versions of Warcraft maps.
Creating new map and modifying object data does the trick, however, taking old maps and tring to inject code in them fails.

**Comment by Drake53** [comment]
I found some maps on epicwar that reproduce the issue (failing to parse the filetypes you mentioned). I'll look into a solution this weekend.

**Comment by Drake53** [comment]
It appears there's a new file format for the war3map.w3s file. I have updated the code to support parsing this new format.
For the object data files I found they fail at the sanity check, which suggests that the file is corrupted. However, when I ignore this failed check it seems to work.

**Comment by Drake53** [comment]
@AzuStar I have updated War3Net.Build to v1.3.5, if you're still having issues do let me know, otherwise you can close the issue.

**Comment by AzuStar** [comment]
Seems to be resolved.
