### ISSUE TITLE
Map.Open does not read object names or tooltips

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Net#43]
When I use `Map.Open`, the resulting `UnitObjectData` collection does not contain the names, tooltips, models, icons, etc of my custom units. The issue extends to all object types aside from Doodad, and seems to apply to all fields in which the user can type a string.

I am able to see the issue using this code, which fails to display the mentioned fields:
```Cs      
      var map = Map.Open(baseMapPath);
      var unitObjectData = map.UnitObjectData;
      foreach (var newUnit in unitObjectData.NewUnits)
      foreach (var mod in newUnit.Modifications)
        Console.WriteLine(mod.Value);
```

I'm using the latest Warcraft 3 version. Please let me know if you need any more information.

**Comment by Drake53** [comment]
One of the Reforged patches (I think it was 1.33) changed object data to be split into two separate files, you should be able to find this data in `Map.UnitSkinObjectData`.

**Comment by YakaryBovine** [comment]
Thankyou, that makes sense. I'll double-check and confirm soon.

**Comment by YakaryBovine** [comment]
The data was indeed in there. Thanks again.
