### ISSUE TITLE
Editing custom tile pathing

### ISSUE THREAD

**Issue by YakaryBovine** [Drake53/War3Net#44]
Hi, you may be aware that it's possible to modify tile pathability in a map by saving the map with a custom terrian.slk file. Tutorial here: https://www.whaven.org/index.php?threads/tutorial-modifying-terrain-pathability-no-extra-programs-needed.4072/

I'm wondering: is it possible to use War3Net programmatically build a map that custom tile pathability?

**Comment by Drake53** [comment]
That method is only useful if you're using the world editor. The pathing actually gets saved as a separate file `war3map.wpm`, which is represented in War3Net as `MapPathingMap`. It'd probably be easier to do this in HiveWE though, which has a pathability editor allowing you to 'override' the pathing that tiles normally have.

**Comment by YakaryBovine** [comment]
Fascinating, thankyou. That answers my question; I can build up the pathing map programmatically by modifying the `PathingMap` property of my map.
